<a href="https://colab.research.google.com/github/HK-Sepuri/My_Learning/blob/main/DL/Computer_Vision_with_Python_and_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [3]:
tensor_zero_d = tf.constant(8)
tensor_zero_d

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [4]:
tensor_one_d = tf.constant([1,2,3,4.0])
tensor_one_d

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

In [5]:
tensor_two_d = tf.constant([[1,2],[2,3],[3,4]])
tensor_two_d

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [3, 4]], dtype=int32)>

In [6]:
tensor_three_d = tf.constant([[[1,2],[2,3],[3,4]],
                              [[1,2],[2,3],[3,4]],
                              [[1,2],[2,3],[3,4]]])
tensor_three_d

<tf.Tensor: shape=(3, 3, 2), dtype=int32, numpy=
array([[[1, 2],
        [2, 3],
        [3, 4]],

       [[1, 2],
        [2, 3],
        [3, 4]],

       [[1, 2],
        [2, 3],
        [3, 4]]], dtype=int32)>

In [7]:
tensor_four_d = tf.constant([[[[1,2],[2,3],[3,4]],
                              [[1,2],[2,3],[3,4]],
                              [[1,2],[2,3],[3,4]]],[[[1,2],[2,3],[3,4]],
                              [[1,2],[2,3],[3,4]],
                              [[1,2],[2,3],[3,4]]]])
tensor_four_d

<tf.Tensor: shape=(2, 3, 3, 2), dtype=int32, numpy=
array([[[[1, 2],
         [2, 3],
         [3, 4]],

        [[1, 2],
         [2, 3],
         [3, 4]],

        [[1, 2],
         [2, 3],
         [3, 4]]],


       [[[1, 2],
         [2, 3],
         [3, 4]],

        [[1, 2],
         [2, 3],
         [3, 4]],

        [[1, 2],
         [2, 3],
         [3, 4]]]], dtype=int32)>

In [10]:
casted_tensor_one_d = tf.cast(tensor_one_d,dtype= tf.int64)
casted_tensor_one_d

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [11]:
boolen_tensor_one_d = tf.cast(tensor_one_d,dtype= bool)
boolen_tensor_one_d

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True,  True,  True,  True])>

In [12]:
# if its zero its false and anyother number will be true

In [14]:
tensor_bool = tf.constant([True,False,True])
tensor_bool

<tf.Tensor: shape=(3,), dtype=bool, numpy=array([ True, False,  True])>

In [15]:
tensor_string = tf.constant(["Hello","world","!"])
tensor_string

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'Hello', b'world', b'!'], dtype=object)>

In [16]:
import numpy as np

In [18]:
np_array = ([1,2,3,4,5,5])
np_array

[1, 2, 3, 4, 5, 5]

In [19]:
tensor_np_array = tf.convert_to_tensor(np_array)
tensor_np_array

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 5], dtype=int32)>

In [20]:
import tensorflow as tf
print(tf.__version__)

2.14.0
