<a href="https://colab.research.google.com/github/HK-Sepuri/My_Learning/blob/main/DL/Deep_learning_with_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("hello world")

hello world


# Import

In [3]:
import torch

In [4]:
print(torch.__version__)

2.0.1+cu118


In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Introduction to Tensors

Creating tensors

Every tensor in pytorch is created using "torch.tesnsor"

In [7]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [10]:
scalar.ndim

0

In [13]:
scalar.item()

7

In [15]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [16]:
vector.ndim

1

In [17]:
vector.shape

torch.Size([2])

In [19]:
#matrix
matrix = torch.tensor([[1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [20]:
matrix.ndim

2

In [21]:
matrix.shape

torch.Size([2, 2])

In [22]:
matrix[0]

tensor([1, 2])

In [23]:
matrix[0][1]

tensor(2)

In [24]:
#tensor
tensor = torch.tensor([[[1,2,3],[4,5,6],[6,7,8]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]])

In [25]:
tensor.ndim

3

In [26]:
tensor.shape

torch.Size([1, 3, 3])

In [27]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]])

In [29]:
tensor1 =torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
tensor1

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])

In [31]:
tensor1.ndim

3

In [32]:
tensor1.shape

torch.Size([3, 3, 3])

First [ says about dim 1 while 2nd [ says aboyt dim 2 and 3rd [ says about dim 3

# Random Tensors

use torch.rand() to create random tensors

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...


In [33]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0240, 0.1940, 0.4557, 0.8517],
        [0.0936, 0.0712, 0.2008, 0.2345],
        [0.2168, 0.3151, 0.4324, 0.0527]])

In [34]:
random_tensor.ndim

2

In [36]:
random_tensor.shape

torch.Size([3, 4])

In [37]:
random_tensor1= torch.rand(3,4,5)
random_tensor1

tensor([[[0.9853, 0.5830, 0.3004, 0.8939, 0.8147],
         [0.6393, 0.5712, 0.6821, 0.1557, 0.8052],
         [0.3159, 0.4767, 0.8541, 0.1199, 0.4021],
         [0.1181, 0.9862, 0.7832, 0.1665, 0.1843]],

        [[0.4394, 0.7483, 0.7112, 0.8350, 0.2430],
         [0.7465, 0.6638, 0.1950, 0.3118, 0.4128],
         [0.0024, 0.9150, 0.0672, 0.2231, 0.7735],
         [0.0027, 0.2812, 0.7881, 0.4315, 0.6960]],

        [[0.4456, 0.8214, 0.4075, 0.5614, 0.8505],
         [0.6884, 0.2964, 0.0835, 0.4033, 0.2496],
         [0.1461, 0.3312, 0.0325, 0.3207, 0.1787],
         [0.9936, 0.4041, 0.1208, 0.4638, 0.3545]]])

In [38]:
random_image_size_tensor = torch.rand(size= (224,224,3)) # height , width and colour channles = red blue and green
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and ones Tensors

In [41]:
zeros = torch.zeros(3,4,5)
zeros

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [42]:
ones = torch.ones(3,4,5)
ones

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [43]:
ones.dtype

torch.float32

# Creating a range and tensors like

In [44]:
torch.range(0,10)

<ipython-input-44-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [46]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arange = torch.arange(start=0,end=1000 , step=108)
arange

tensor([  0, 108, 216, 324, 432, 540, 648, 756, 864, 972])

In [48]:
torch_like= torch.zeros_like(input=arange)
torch_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatyepe

In [49]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [52]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor.dtype

torch.float16