<a href="https://colab.research.google.com/github/HK-Sepuri/My_Learning/blob/main/DL/Deep_learning_with_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello world")

hello world


# Import

In [ ]:
import torch

In [ ]:
print(torch.__version__)

2.0.1+cu118


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Introduction to Tensors

Creating tensors

Every tensor in pytorch is created using "torch.tesnsor"

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix
matrix = torch.tensor([[1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
matrix[0]

tensor([1, 2])

In [ ]:
matrix[0][1]

tensor(2)

In [ ]:
#tensor
tensor = torch.tensor([[[1,2,3],[4,5,6],[6,7,8]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]])

In [ ]:
tensor1 =torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
tensor1

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])

In [ ]:
tensor1.ndim

3

In [ ]:
tensor1.shape

torch.Size([3, 3, 3])

First [ says about dim 1 while 2nd [ says aboyt dim 2 and 3rd [ says about dim 3

# Random Tensors

use torch.rand() to create random tensors

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...


In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1866, 0.3129, 0.2455, 0.3420],
        [0.9615, 0.1810, 0.8832, 0.7504],
        [0.1753, 0.1168, 0.6136, 0.5039]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
random_tensor1= torch.rand(3,4,5)
random_tensor1

tensor([[[0.4369, 0.9870, 0.9129, 0.9253, 0.7621],
         [0.6529, 0.8210, 0.2429, 0.5004, 0.1196],
         [0.5905, 0.3215, 0.7260, 0.2813, 0.9378],
         [0.6900, 0.9202, 0.8346, 0.0383, 0.0370]],

        [[0.6917, 0.5823, 0.1955, 0.8965, 0.9430],
         [0.2574, 0.2223, 0.7049, 0.1191, 0.6043],
         [0.4381, 0.0457, 0.5443, 0.7446, 0.7612],
         [0.2267, 0.0050, 0.3950, 0.8020, 0.6169]],

        [[0.4834, 0.9531, 0.1149, 0.1341, 0.7876],
         [0.1589, 0.0916, 0.0135, 0.1286, 0.9438],
         [0.0961, 0.7226, 0.6142, 0.0903, 0.5047],
         [0.0672, 0.2248, 0.4825, 0.6040, 0.1857]]])

In [ ]:
random_image_size_tensor = torch.rand(size= (224,224,3)) # height , width and colour channles = red blue and green
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and ones Tensors

In [ ]:
zeros = torch.zeros(3,4,5)
zeros

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [ ]:
ones = torch.ones(3,4,5)
ones

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [ ]:
ones.dtype

torch.float32

# Creating a range and tensors like

In [ ]:
torch.range(0,10)

<ipython-input-31-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arange = torch.arange(start=0,end=1000 , step=108)
arange

tensor([  0, 108, 216, 324, 432, 540, 648, 756, 864, 972])

In [ ]:
torch_like= torch.zeros_like(input=arange)
torch_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatyepe

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type(cpu,gpu,tpu)
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor.dtype

torch.float16

# Getting information from tensors

Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.


    shape - what shape is the tensor? (some operations require specific shape rules)
    dtype - what datatype are the elements within the tensor stored in?
    device - what device is the tensor stored on? (usually GPU or CPU)


In [ ]:
some_tensor = torch.rand(3,4)

In [ ]:
some_tensor , some_tensor.shape, some_tensor.ndim

(tensor([[0.6636, 0.2193, 0.9814, 0.0066],
         [0.8325, 0.3868, 0.6604, 0.6508],
         [0.8894, 0.5448, 0.6005, 0.8471]]),
 torch.Size([3, 4]),
 2)

In [ ]:
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Manipulating tensors (tensor operations)


    Addition
    Substraction
    Multiplication (element-wise)
    Division
    Matrix multiplication


In [ ]:
a = torch.tensor([1,2,3])
a +10

tensor([11, 12, 13])

In [ ]:
a*10

tensor([10, 20, 30])

In [ ]:
a-10

tensor([-9, -8, -7])

In [ ]:
torch.mul(a,10)

tensor([10, 20, 30])

In [ ]:
a

tensor([1, 2, 3])

In [ ]:
torch.add(a,10)

tensor([11, 12, 13])

# Matrix multiplication

In [ ]:
b = torch.tensor([1,2,3])
b, b.shape

(tensor([1, 2, 3]), torch.Size([3]))

In [ ]:
b * b

tensor([1, 4, 9])

In [ ]:
# Matrix multiplication
torch.matmul(b, b)

tensor(14)

Element-wise multiplication 	[1*1, 2*2, 3*3] = [1, 4, 9] 	tensor * tensor

Matrix multiplication 	[1*1 + 2*2 + 3*3] = [14] 	tensor.matmul(tensor)

In [ ]:
b @ b

tensor(14)

In [ ]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(b)):
  value += b[i] * b[i]
value

CPU times: user 3.26 ms, sys: 727 µs, total: 3.99 ms
Wall time: 4.01 ms


tensor(14)

In [ ]:
%%time
torch.matmul(b, b)

CPU times: user 1.14 ms, sys: 11 µs, total: 1.15 ms
Wall time: 1.19 ms


tensor(14)

In [ ]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

In [ ]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
# Shapes need to be in the right way
torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: ignored

You can perform transposes in PyTorch using either:

    torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
    tensor.T - where tensor is the desired tensor to transpose.


In [ ]:
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [ ]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

# Finding the min, max, mean, sum, etc (aggregation)

In [ ]:
c = torch.arange(0,100,10)
c

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(f"Minimum: {c.min()}")
print(f"Maximum: {c.max()}")
# print(f"Mean: {c.mean()}") # this will error
print(f"Mean: {c.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {c.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [ ]:
torch.max(c), torch.min(c), torch.mean(c.type(torch.float32)), torch.sum(c)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [ ]:
c.argmax(), c.argmin() # position of min and max values

(tensor(9), tensor(0))

# Change tensor datatype

In [ ]:
tensor = torch.arange(10., 100., 10.)
tensor, tensor.dtype

(tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.]), torch.float32)

In [ ]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

# Reshaping, stacking, squeezing and unsqueezing

In [ ]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))



Remember though, changing the view of a tensor with torch.view() really only creates a new view of the same tensor.

So changing the view changes the original tensor too.


In [ ]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [ ]:
x

tensor([5., 2., 3., 4., 5., 6., 7.])

In [ ]:
x_reshaped_1 = x.reshape(7, 1)
x_reshaped_1, x_reshaped_1.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.]]),
 torch.Size([7, 1]))

Removing all single dimensions from a tensor?

To do so you can use torch.squeeze()


In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


And to do the reverse of torch.squeeze() you can use torch.unsqueeze() to add a dimension value of 1 at a specific index.

In [ ]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [ ]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


# Indexing (selecting data from tensors)

In [1]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [2]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [3]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [4]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [5]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [6]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

# PyTorch tensors & NumPy


    torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
    torch.Tensor.numpy() - PyTorch tensor -> NumPy array.


In [7]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [8]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [9]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [10]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility (trying to take the random out of random)

In [11]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.7477, 0.8034, 0.8194, 0.0033],
        [0.0437, 0.4308, 0.0931, 0.4147],
        [0.5036, 0.4065, 0.5217, 0.1320]])

Tensor B:
tensor([[0.2808, 0.6328, 0.0725, 0.7130],
        [0.9472, 0.3067, 0.5115, 0.7824],
        [0.7142, 0.5650, 0.4632, 0.5494]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])