<a href="https://colab.research.google.com/github/HK-Sepuri/My_Learning/blob/main/DL/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello world")

hello world


# Import

In [ ]:
import torch

In [ ]:
print(torch.__version__)

2.0.1+cu118


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Introduction to Tensors

Creating tensors

Every tensor in pytorch is created using "torch.tesnsor"

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix
matrix = torch.tensor([[1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
matrix[0]

tensor([1, 2])

In [ ]:
matrix[0][1]

tensor(2)

In [ ]:
#tensor
tensor = torch.tensor([[[1,2,3],[4,5,6],[6,7,8]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]])

In [ ]:
tensor1 =torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
tensor1

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])

In [ ]:
tensor1.ndim

3

In [ ]:
tensor1.shape

torch.Size([3, 3, 3])

First [ says about dim 1 while 2nd [ says aboyt dim 2 and 3rd [ says about dim 3

# Random Tensors

use torch.rand() to create random tensors

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...


In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1866, 0.3129, 0.2455, 0.3420],
        [0.9615, 0.1810, 0.8832, 0.7504],
        [0.1753, 0.1168, 0.6136, 0.5039]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
random_tensor1= torch.rand(3,4,5)
random_tensor1

tensor([[[0.4369, 0.9870, 0.9129, 0.9253, 0.7621],
         [0.6529, 0.8210, 0.2429, 0.5004, 0.1196],
         [0.5905, 0.3215, 0.7260, 0.2813, 0.9378],
         [0.6900, 0.9202, 0.8346, 0.0383, 0.0370]],

        [[0.6917, 0.5823, 0.1955, 0.8965, 0.9430],
         [0.2574, 0.2223, 0.7049, 0.1191, 0.6043],
         [0.4381, 0.0457, 0.5443, 0.7446, 0.7612],
         [0.2267, 0.0050, 0.3950, 0.8020, 0.6169]],

        [[0.4834, 0.9531, 0.1149, 0.1341, 0.7876],
         [0.1589, 0.0916, 0.0135, 0.1286, 0.9438],
         [0.0961, 0.7226, 0.6142, 0.0903, 0.5047],
         [0.0672, 0.2248, 0.4825, 0.6040, 0.1857]]])

In [ ]:
random_image_size_tensor = torch.rand(size= (224,224,3)) # height , width and colour channles = red blue and green
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and ones Tensors

In [ ]:
zeros = torch.zeros(3,4,5)
zeros

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [ ]:
ones = torch.ones(3,4,5)
ones

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [ ]:
ones.dtype

torch.float32

# Creating a range and tensors like

In [ ]:
torch.range(0,10)

<ipython-input-31-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arange = torch.arange(start=0,end=1000 , step=108)
arange

tensor([  0, 108, 216, 324, 432, 540, 648, 756, 864, 972])

In [ ]:
torch_like= torch.zeros_like(input=arange)
torch_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatyepe

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type(cpu,gpu,tpu)
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor.dtype

torch.float16

# Getting information from tensors

Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.


    shape - what shape is the tensor? (some operations require specific shape rules)
    dtype - what datatype are the elements within the tensor stored in?
    device - what device is the tensor stored on? (usually GPU or CPU)


In [ ]:
some_tensor = torch.rand(3,4)

In [ ]:
some_tensor , some_tensor.shape, some_tensor.ndim

(tensor([[0.6636, 0.2193, 0.9814, 0.0066],
         [0.8325, 0.3868, 0.6604, 0.6508],
         [0.8894, 0.5448, 0.6005, 0.8471]]),
 torch.Size([3, 4]),
 2)

In [ ]:
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Manipulating tensors (tensor operations)


    Addition
    Substraction
    Multiplication (element-wise)
    Division
    Matrix multiplication


In [ ]:
a = torch.tensor([1,2,3])
a +10

tensor([11, 12, 13])

In [ ]:
a*10

tensor([10, 20, 30])

In [ ]:
a-10

tensor([-9, -8, -7])

In [ ]:
torch.mul(a,10)

tensor([10, 20, 30])

In [ ]:
a

tensor([1, 2, 3])

In [ ]:
torch.add(a,10)

tensor([11, 12, 13])

# Matrix multiplication

In [ ]:
b = torch.tensor([1,2,3])
b, b.shape

(tensor([1, 2, 3]), torch.Size([3]))

In [ ]:
b * b

tensor([1, 4, 9])

In [ ]:
# Matrix multiplication
torch.matmul(b, b)

tensor(14)

Element-wise multiplication 	[1*1, 2*2, 3*3] = [1, 4, 9] 	tensor * tensor

Matrix multiplication 	[1*1 + 2*2 + 3*3] = [14] 	tensor.matmul(tensor)

In [ ]:
b @ b

tensor(14)

In [ ]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(b)):
  value += b[i] * b[i]
value

CPU times: user 3.26 ms, sys: 727 µs, total: 3.99 ms
Wall time: 4.01 ms


tensor(14)

In [ ]:
%%time
torch.matmul(b, b)

CPU times: user 1.14 ms, sys: 11 µs, total: 1.15 ms
Wall time: 1.19 ms


tensor(14)

In [ ]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

In [ ]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
# Shapes need to be in the right way
torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: ignored

You can perform transposes in PyTorch using either:

    torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
    tensor.T - where tensor is the desired tensor to transpose.


In [ ]:
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [ ]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

# Finding the min, max, mean, sum, etc (aggregation)

In [ ]:
c = torch.arange(0,100,10)
c

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(f"Minimum: {c.min()}")
print(f"Maximum: {c.max()}")
# print(f"Mean: {c.mean()}") # this will error
print(f"Mean: {c.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {c.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [ ]:
torch.max(c), torch.min(c), torch.mean(c.type(torch.float32)), torch.sum(c)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [ ]:
c.argmax(), c.argmin() # position of min and max values

(tensor(9), tensor(0))

# Change tensor datatype

In [ ]:
tensor = torch.arange(10., 100., 10.)
tensor, tensor.dtype

(tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.]), torch.float32)

In [ ]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

# Reshaping, stacking, squeezing and unsqueezing

In [ ]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))



Remember though, changing the view of a tensor with torch.view() really only creates a new view of the same tensor.

So changing the view changes the original tensor too.


In [ ]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [ ]:
x

tensor([5., 2., 3., 4., 5., 6., 7.])

In [ ]:
x_reshaped_1 = x.reshape(7, 1)
x_reshaped_1, x_reshaped_1.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.]]),
 torch.Size([7, 1]))

Removing all single dimensions from a tensor?

To do so you can use torch.squeeze()


In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


And to do the reverse of torch.squeeze() you can use torch.unsqueeze() to add a dimension value of 1 at a specific index.

In [ ]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [ ]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


# Indexing (selecting data from tensors)

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [ ]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

# PyTorch tensors & NumPy


    torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
    torch.Tensor.numpy() - PyTorch tensor -> NumPy array.


In [ ]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility (trying to take the random out of random)

In [ ]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.7477, 0.8034, 0.8194, 0.0033],
        [0.0437, 0.4308, 0.0931, 0.4147],
        [0.5036, 0.4065, 0.5217, 0.1320]])

Tensor B:
tensor([[0.2808, 0.6328, 0.0725, 0.7130],
        [0.9472, 0.3067, 0.5115, 0.7824],
        [0.7142, 0.5650, 0.4632, 0.5494]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# Running tensors on GPUs (and making faster computations)

In [ ]:
!nvidia-smi

Thu Oct 19 08:26:04 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   61C    P8    12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [ ]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

In [ ]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

In [ ]:
# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

Notice the second tensor has device='cuda:0', this means it's stored on the 0th GPU available (GPUs are 0 indexed, if two GPUs were available, they'd be 'cuda:0' and 'cuda:1' respectively, up to 'cuda:n').

In [ ]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: ignored

In [ ]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu
# The above returns a copy of the GPU tensor in CPU memory so the original tensor is still on GPU.

tensor([1, 2, 3], device='cuda:0')

# Exercises for the stuff we learnt till now

In [ ]:
# Create a random tensor with shape (7, 7).
import torch
a= torch.rand(7,7)
a

tensor([[0.4100, 0.8832, 0.2426, 0.6913, 0.5573, 0.4034, 0.8743],
        [0.4452, 0.0136, 0.9133, 0.5663, 0.7556, 0.3367, 0.3187],
        [0.6287, 0.4999, 0.9515, 0.7990, 0.4656, 0.4846, 0.1108],
        [0.2735, 0.8538, 0.2264, 0.8803, 0.9795, 0.5021, 0.4795],
        [0.9383, 0.0388, 0.0130, 0.2538, 0.1005, 0.2494, 0.4566],
        [0.8485, 0.9642, 0.4843, 0.1642, 0.0109, 0.6371, 0.3214],
        [0.2700, 0.5189, 0.9010, 0.7943, 0.2520, 0.5744, 0.9887]])

In [ ]:
# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

b= torch.rand(1,7)
b

tensor([[0.7038, 0.0169, 0.3436, 0.0303, 0.2054, 0.8155, 0.1376]])

In [ ]:
torch.mm(a,b.T)

tensor([[0.9716],
        [1.1182],
        [1.3082],
        [0.9880],
        [0.9600],
        [1.3509],
        [1.1887]])

In [ ]:
#Set the random seed to 0 and do exercises  over again.

RANDOM_SEED = 0

torch.manual_seed(seed=RANDOM_SEED)
a= torch.rand(7,7)

torch.manual_seed(seed=RANDOM_SEED)
b= torch.rand(1,7)

a,b , torch.mm(a,b.T)

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]]),
 tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]))

In [ ]:
# random seed for GPU
#torch.cuda.manual_seed(seed)

In [ ]:
import torch

# Set the GPU random seed to 1234
torch.cuda.manual_seed(1234)

In [ ]:
#Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [ ]:
# Set the random seed
torch.manual_seed(1234)

# Create two random tensors on CPU
random_tensor1 = torch.rand(2, 3)
random_tensor2 = torch.rand(2, 3)

# Send them to the GPU
random_tensor1 = random_tensor1.to('cuda')
random_tensor2 = random_tensor2.to('cuda')

In [ ]:
random_tensor1, random_tensor2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [ ]:
# Perform a matrix multiplication on the tensors you created

random_tensor3 = torch.mm(random_tensor1,random_tensor2.T)
random_tensor3

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

In [ ]:
# Find the maximum and minimum values of the output of 7.

random_tensor3.max(), random_tensor3.min()

(tensor(0.6287, device='cuda:0'), tensor(0.2161, device='cuda:0'))

In [ ]:
torch.min(random_tensor3),torch.max(random_tensor3)

(tensor(0.2161, device='cuda:0'), tensor(0.6287, device='cuda:0'))

In [ ]:
# Find the maximum and minimum index values of the output of 7.
torch.argmax(random_tensor3),torch.argmin(random_tensor3)

(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))

In [ ]:
# Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a
# tensor of shape (10).
# Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
