# Numpy 

In [1]:
#numerical Python 

In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3], dtype='int32') # adding list to arry and defining the type 
print(a)

[1 2 3]


In [6]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]]) # adding a 2d array 
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# Get Dimension
a.ndim

1

In [8]:
b.ndim

2

In [9]:
# Get Shape
b.shape

(2, 3)

In [10]:
a.shape

(3,)

In [11]:
# Get Type
a.dtype

dtype('int32')

In [12]:
b.dtype

dtype('float64')

In [13]:
# Get Size
a.itemsize

4

In [14]:
b.itemsize

8

In [15]:
# Get total size
a.nbytes

12

In [16]:
b.nbytes

48

In [17]:
# Get number of elements
a.size

3

In [18]:
b.size

6

# Accessing/Changing specific elements, rows, columns, etc

In [35]:
# we defined a 2d array
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
# Get a specific element [row, column]
a[1, 5]

13

In [24]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [27]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6]

array([2, 3, 4, 5, 6])

In [31]:
a[0,1:6:2]# 1st row from 1 to 6 column and skipping every 2nd element

array([2, 4, 6])

In [36]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]# here negative means from right side not left side so -1 from right will be 6

array([2, 4, 6])

In [38]:
a[1,5] = 20 # changed a spefic element
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [39]:
a[:,2] = [1,2]
print(a) # changed a spefic column

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [40]:
#3d array

In [41]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [44]:
b.dtype

dtype('int64')

In [43]:
b.shape

(2, 2, 2)

In [45]:
# Get specific element (work left to right)
b[0,1,1]

4

In [46]:
# replace 
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [47]:
b[:,1,:] = [[9,9],[8,8]]# it should be on same dimensiion to work 

In [48]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [50]:
b[:,1,:] =[[1,1,1],[2,2]]# if not same dimenssion it wont work

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

# Initializing Different Types of Arrays

In [57]:
# All 0's matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [56]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [58]:
# All 1's matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [59]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [60]:
np.full((3,3),108)

array([[108, 108, 108],
       [108, 108, 108],
       [108, 108, 108]])

In [63]:
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [65]:
# Any other number (full_like)
np.full_like(a, 4)# takes shape of a and fill it with element 4

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [66]:
np.full_like(a,100)

array([[100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100]])

In [68]:
# np.random.rand create random number between 0-1

In [67]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.27957615, 0.27887417],
       [0.049628  , 0.86510774],
       [0.94070415, 0.73063784],
       [0.11480126, 0.12657522]])

In [69]:
np.random.rand(4,4)

array([[0.96941902, 0.2377201 , 0.96872641, 0.4988884 ],
       [0.15913308, 0.92990096, 0.39141237, 0.35010592],
       [0.36473815, 0.90914416, 0.47298939, 0.42984404],
       [0.42425607, 0.70839905, 0.22573758, 0.85654044]])

In [71]:
# created random values based on the given range
# Random Integer values
np.random.randint(-4,8, size=(4,4))

array([[ 5, -4,  0,  1],
       [ 3,  3,  7, -1],
       [-1,  5,  5, -4],
       [ 7,  3,  6,  5]])

In [72]:
# The identity matrix is nxn matrix and fill only the diagonal 
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [73]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [76]:
# Repeat an array
arr = np.array([[1,2,3]])
arr

array([[1, 2, 3]])

In [77]:
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [82]:
r1=np.repeat(arr,3,axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [83]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [84]:
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [85]:
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [87]:
output[1:-1,1:-1] = z# here we have placed the whole value of z into output 
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [90]:
h=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [91]:
h

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
output[1:-1,1:-1] =h
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 2. 3. 1.]
 [1. 4. 5. 6. 1.]
 [1. 7. 8. 9. 1.]
 [1. 1. 1. 1. 1.]]


In [94]:
#when we use copy funtion only values get copy not the loctaion 

a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


# Mathematics

In [95]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [96]:
a+2

array([3, 4, 5, 6])

In [97]:
a-2

array([-1,  0,  1,  2])

In [98]:
a*2

array([2, 4, 6, 8])

In [99]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [100]:
a**a

array([  1,   4,  27, 256])

In [101]:
a**2

array([ 1,  4,  9, 16])

In [104]:
b = np.array([1,0,1,0])

In [105]:
a+b

array([2, 2, 4, 4])

In [106]:
a-b

array([0, 2, 2, 4])

In [107]:
a*b

array([1, 0, 3, 0])

In [108]:
a/b

/tmp/ipykernel_32677/1348051284.py:1: RuntimeWarning: divide by zero encountered in divide
  a/b


array([ 1., inf,  3., inf])

In [109]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [110]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [111]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

# Linear Algebra

In [112]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [113]:
b = np.full((3,2), 2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [114]:
a*b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [115]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [116]:
# Find the determinant
c = np.identity(3)

In [117]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [118]:
np.linalg.det(c)

1.0

In [119]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

# Statistics

In [120]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [121]:
np.min(stats)

1

In [125]:
np.shape(stats)

(2, 3)

In [126]:
np.max(stats)

6

In [128]:
np.min(stats, axis=1)#min of first row and min or 2nd row 

array([1, 4])

In [130]:
np.min(stats, axis=0)#min of all column

array([1, 2, 3])

In [131]:
np.max(stats, axis=1)

array([3, 6])

In [132]:
np.max(stats, axis=0)

array([4, 5, 6])

In [135]:
np.sum(stats, axis=0) # in row add all column elements

array([5, 7, 9])

In [136]:
np.sum(stats, axis=1)# in coloum all all row elements

array([ 6, 15])

# Reorganizing Arrays

In [137]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [139]:
np.shape(before)

(2, 4)

In [140]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [141]:
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [142]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [143]:
after = before.reshape((2,3))# wrong no of elements 
print(after)

ValueError: cannot reshape array of size 8 into shape (2,3)

In [146]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [147]:
np.vstack([v1,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [148]:
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [150]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

print(h1)
print(h2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


In [151]:
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

In [156]:
np.genfromtxt('data.txt', delimiter=',') # need to be in same folder as the file or need to create file path

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [157]:
# np.genfromtxt('/full/path/to/data.txt', delimiter=',')

In [158]:
filedata = np.genfromtxt('/home/hari/Desktop/Python/Learning/data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [159]:
# Boolean Masking and Advanced Indexing

In [161]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [162]:
filedata < 100

array([[ True,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [163]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [169]:
a=np.array([1,2,3,4,5,6,7,8,9])
a[[2,3,8]]

array([3, 4, 9])

In [174]:
np.any(filedata>50, axis=0) #in row checks if any cloumn elements is true or flase

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [173]:
np.all(filedata>50, axis=0)# in row checks allcolumn elements

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [175]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [177]:
(~((filedata > 50) & (filedata < 100))) #~ means not 

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])